"""add provider config columns to instances

Revision ID: 1d0a44d56206
Revises: 
Create Date: 2026-07-04 02:22:30.655252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0a44d56206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_CREATED', 'CREATING', 'SLEEPING', 'STARTING', 'RUNNING', 'STOPPING', 'ERROR', 'DELETING', name='instancestatus'), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'PAID_RESIDENT', name='plantype'), nullable=True),
    sa.Column('container_name', sa.String(), nullable=True),
    sa.Column('volume_name', sa.String(), nullable=True),
    sa.Column('assigned_port', sa.Integer(), nullable=True),
    sa.Column('provider_config_enc', sa.Text(), nullable=True),
    sa.Column('provider_config_alg', sa.String(length=32), nullable=True),
    sa.Column('provider_key_set_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('instance_id')
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PAID_RESIDENT', name='plantype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workspace_states',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.instance_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_states')
    op.drop_table('users')
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_user_id'))

    op.drop_table('instances')
    # ### end Alembic commands ###
