name: Mirror to GitLab

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Push mirror
        run: |
          git clone --mirror "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" repo.git
          cd repo.git
          git remote set-url --push origin "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/ruciwunai/savvy.git"
          git push --mirror origin
        env:
          GIT_TERMINAL_PROMPT: '0'
